import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Activity, Atom, BookOpen, Download, FileUp, Layers3, Plus, Settings2, Trash2, Waves } from "lucide-react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import katex from "katex";
import type { Layer, Project, Result } from "./types";

const materials = ["Si","Ge","SiGe","SiO2","GaAs","AlAs","InAs","AlGaAs","InGaAs","AlInAs","InP","GaP","AlP","InGaP","GaN","AlN","InN","AlGaN","InGaN"];
const fallback: Project = { schema_version:1,name:"PN diode",description:"One-dimensional silicon junction",temperature_k:300,mesh_spacing_nm:5,fully_ionized:true,
  layers:[{name:"P region",material:"Si",thickness_nm:500,alloy_fraction:null,donors_cm3:0,acceptors_cm3:1e16,sheet_charge_cm2:0,mesh_spacing_nm:null},{name:"N region",material:"Si",thickness_nm:500,alloy_fraction:null,donors_cm3:1e16,acceptors_cm3:0,sheet_charge_cm2:0,mesh_spacing_nm:null}],
  surface:{kind:"ohmic",barrier_ev:0,voltage_v:0},substrate:{kind:"ohmic",barrier_ev:0,voltage_v:0},quantum:null,sweep:{enabled:true,start_v:-1,stop_v:.7,step_v:.1},solver:{max_iterations:400,tolerance:1e-7,mixing:.18,preview_scale:4} };

type Theme = "mocha"|"latte"|"macchiato"|"tokyo"|"gruvbox";
type ChartKind = "bands"|"carriers"|"field"|"wave"|"sweep";
type Pane = "project"|"structure"|"quantum"|"settings"|"learn";

function SharkLogo(){return <svg className="shark-logo" viewBox="0 0 64 64" aria-label="Requin shark"><path d="M6 35c9-14 21-21 36-21 7 0 13 2 17 5l-9 11 9 11c-5 3-11 5-18 5-14 0-26-7-35-21l7 10-7 10z"/><path className="fin" d="M28 16 39 4l4 12M29 45l8 12 5-13"/><circle cx="43" cy="23" r="2.2"/></svg>}

function MathText({tex}:{tex:string}) { return <span dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{throwOnError:false})}}/> }
function n(v:number,digits=3){ if(!Number.isFinite(v)) return "—"; return Math.abs(v)>=1e4||Math.abs(v)<1e-2&&v!==0?v.toExponential(2):v.toFixed(digits) }
function download(name:string,content:string,type="text/plain") { const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }

function NumberInput({label,value,onChange,unit,step="any"}:{label:string,value:number,onChange:(v:number)=>void,unit?:string,step?:number|string}) {
  return <label className="field"><span>{label}</span><div><input type="number" step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/>{unit&&<em>{unit}</em>}</div></label>
}

function Plot({kind,result}:{kind:ChartKind,result:Result}) {
  const data=useMemo(()=>{
    if(kind==="sweep") return result.sweep.map(p=>({x:p.voltage_v,a:p.current_a_m2,b:p.capacitance_f_m2}));
    const stride=Math.max(1,Math.ceil(result.position_nm.length/1200));
    return result.position_nm.flatMap((x,i)=>i%stride?[]:[{x,a:kind==="bands"?result.conduction_band_ev[i]:kind==="carriers"?Math.max(result.electron_cm3[i],1):kind==="field"?result.electric_field_v_cm[i]:result.eigenstates[0]?.wavefunction[i]??0,b:kind==="bands"?result.valence_band_ev[i]:kind==="carriers"?Math.max(result.hole_cm3[i],1):null}]);
  },[kind,result]);
  const log=kind==="carriers";
  const labels=kind==="bands"?["E_c","E_v"]:kind==="carriers"?["n","p"]:kind==="field"?["E",""]:kind==="wave"?["\\psi_1",""]:["J","C"];
  return <div className="plot"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:18,right:24,bottom:24,left:18}}>
    <CartesianGrid stroke="var(--grid)" vertical={false}/><XAxis dataKey="x" type="number" domain={["dataMin","dataMax"]} tick={{fill:"var(--muted)",fontSize:11}} label={{value:kind==="sweep"?"Voltage (V)":"Position (nm)",position:"insideBottom",offset:-15,fill:"var(--muted)"}}/>
    <YAxis scale={log?"log":"auto"} domain={log?["auto","auto"]:["auto","auto"]} tick={{fill:"var(--muted)",fontSize:11}} width={72}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:8}}/><ReferenceLine y={0} stroke="var(--border)"/>
    <Line type="monotone" dataKey="a" name={labels[0]} stroke="var(--blue)" dot={false} strokeWidth={2}/>{data.some(d=>d.b!=null)&&<Line type="monotone" dataKey="b" name={labels[1]} stroke="var(--mauve)" dot={false} strokeWidth={2}/>} </LineChart></ResponsiveContainer></div>
}

function App(){
  const [project,setProject]=useState<Project>(fallback); const [result,setResult]=useState<Result|null>(null); const [status,setStatus]=useState("Initializing"); const [error,setError]=useState("");
  const [theme,setTheme]=useState<Theme>(()=>(localStorage.getItem("requin.theme") as Theme)||"mocha"); const [fontScale,setFontScale]=useState(()=>Number(localStorage.getItem("requin.fontScale"))||100); const [density,setDensity]=useState<"comfortable"|"compact">(()=>localStorage.getItem("requin.density")==="compact"?"compact":"comfortable");
  const [pane,setPane]=useState<Pane>("structure"); const [chart,setChart]=useState<ChartKind>("bands"); const [selected,setSelected]=useState(0); const generation=useRef(0); const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{invoke<Project>("default_project").then(setProject).catch(()=>setProject(fallback))},[]);
  useEffect(()=>{localStorage.setItem("requin.theme",theme);localStorage.setItem("requin.fontScale",String(fontScale));localStorage.setItem("requin.density",density)},[theme,fontScale,density]);
  useEffect(()=>{
    const id=++generation.current; setStatus("Input changed · preview pending"); setError("");
    const preview=window.setTimeout(()=>{setStatus("Solving preview…");invoke<Result>("run_simulation",{project,quality:"preview"}).then(r=>{if(id===generation.current){setResult(r);setStatus("Preview · refining…")}}).catch(e=>{if(id===generation.current){setError(String(e));setStatus("Invalid or failed")}})},180);
    const full=window.setTimeout(()=>{setStatus("Solving full model…");invoke<Result>("run_simulation",{project,quality:"full"}).then(r=>{if(id===generation.current){setResult(r);setStatus(r.convergence.converged?"Converged":"Not converged")}}).catch(e=>{if(id===generation.current){setError(String(e));setStatus("Solve failed")}})},900);
    return()=>{clearTimeout(preview);clearTimeout(full)};
  },[project]);
  const patch=(p:Partial<Project>)=>setProject(v=>({...v,...p}));
  const patchLayer=(i:number,p:Partial<Layer>)=>setProject(v=>({...v,layers:v.layers.map((l,j)=>j===i?{...l,...p}:l)}));
  const layer=project.layers[selected]??project.layers[0];
  const importFile=async(file:File)=>{const source=await file.text(); try {const value=file.name.endsWith(".toml")?await invoke<Project>("parse_project_toml",{source}):(await invoke<{project:Project,warnings:string[]}>("import_legacy_deck",{source,name:file.name.replace(/\.[^.]+$/,"")})).project; setProject(value);setSelected(0)}catch(e){setError(String(e))}};
  const save=async()=>{try{download(`${project.name.replace(/\s+/g,"_")}.requin.toml`,await invoke<string>("serialize_project",{project}))}catch(e){setError(String(e))}};
  const csv=()=>{if(!result)return; const rows=["position_nm,potential_v,electric_field_v_cm,conduction_band_ev,valence_band_ev,electron_cm3,hole_cm3,net_charge_cm3,material",...result.position_nm.map((x,i)=>[x,result.potential_v[i],result.electric_field_v_cm[i],result.conduction_band_ev[i],result.valence_band_ev[i],result.electron_cm3[i],result.hole_cm3[i],result.net_charge_cm3[i],JSON.stringify(result.material[i])].join(","))];download(`${project.name}_profiles.csv`,rows.join("\n"),"text/csv")};
  const svg=()=>{const node=document.querySelector(".figure .recharts-wrapper svg");if(!node)return;const copy=node.cloneNode(true) as SVGElement;copy.setAttribute("xmlns","http://www.w3.org/2000/svg");download(`${project.name}_${chart}.svg`,new XMLSerializer().serializeToString(copy),"image/svg+xml")};
  const paneTitles:Record<Pane,[string,string]>={project:["PROJECT","Files and starting points"],structure:["STRUCTURE","Layer stack and experiment"],quantum:["QUANTUM","Effective-mass states"],settings:["SETTINGS","Solver and appearance"],learn:["LEARN / ABOUT","Using Requin"]};
  return <main data-theme={theme} data-density={density} style={{"--font-scale":fontScale/100} as CSSProperties}>
    <aside className="rail"><div className="brand" title="Requin"><SharkLogo/></div><button className={pane==="project"?"active":""} onClick={()=>setPane("project")} title="Project"><Activity/></button><button className={pane==="structure"?"active":""} onClick={()=>setPane("structure")} title="Structure"><Layers3/></button><button className={pane==="quantum"?"active":""} onClick={()=>setPane("quantum")} title="Quantum"><Atom/></button><button className={pane==="settings"?"active":""} onClick={()=>setPane("settings")} title="Settings"><Settings2/></button><span/><button className={pane==="learn"?"active":""} onClick={()=>setPane("learn")} title="Learn and About"><BookOpen/></button></aside>
    <section className="sidebar">
      <header className="pane-header"><div><small>{paneTitles[pane][0]}</small><b>{paneTitles[pane][1]}</b></div></header>
      {pane==="project"&&<div className="pane-content"><label className="field"><span>Project name</span><div><input value={project.name} onChange={e=>patch({name:e.target.value})}/></div></label><label className="field"><span>Description</span><div><input value={project.description} placeholder="What is being studied?" onChange={e=>patch({description:e.target.value})}/></div></label><div className="template"><small>DEVICE TEMPLATE</small><select defaultValue="" onChange={e=>{if(e.target.value)invoke<Project>("project_template",{kind:e.target.value}).then(p=>{setProject(p);setSelected(0)})}}><option value="" disabled>Choose a starting point…</option><option value="pn">PN diode</option><option value="schottky">Schottky diode</option><option value="mos">MOS capacitor</option><option value="hemt">GaAs / AlGaAs HEMT</option><option value="well">Quantum well</option><option value="heterojunction">Heterojunction</option></select></div><div className="side-actions"><button onClick={()=>input.current?.click()}><FileUp/> Import deck or project</button><button onClick={save}><Download/> Save project</button></div><input ref={input} hidden type="file" accept=".txt,.toml,.requin" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><div className="info-card"><small>CURRENT DEVICE</small><b>{project.layers.length} layers · {n(project.layers.reduce((s,l)=>s+l.thickness_nm,0),1)} nm</b><p>{project.quantum?"Quantum region enabled":"Classical electrostatics"} · {project.sweep.enabled?"voltage sweep enabled":"single bias"}</p></div></div>}
      {pane==="structure"&&<><div className="section-title"><span>Layer stack</span><button onClick={()=>setProject(v=>({...v,layers:[...v.layers,{...fallback.layers[0],name:`Layer ${v.layers.length+1}`}]}))}><Plus/> Add</button></div><div className="layers">{project.layers.map((l,i)=><button key={i} className={selected===i?"selected":""} onClick={()=>setSelected(i)}><i style={{background:l.material.includes("Ga")?"var(--mauve)":l.material.includes("O2")?"var(--blue)":"var(--green)"}}/><span><b>{l.name}</b><small>{l.material} · {n(l.thickness_nm,1)} nm</small></span></button>)}</div>{layer&&<div className="editor"><div className="editor-head"><b>Layer {selected+1}</b><button disabled={project.layers.length<2} onClick={()=>{setProject(v=>({...v,layers:v.layers.filter((_,i)=>i!==selected)}));setSelected(Math.max(0,selected-1))}}><Trash2/></button></div><label className="field"><span>Name</span><div><input value={layer.name} onChange={e=>patchLayer(selected,{name:e.target.value})}/></div></label><label className="field"><span>Material</span><div><select value={layer.material} onChange={e=>patchLayer(selected,{material:e.target.value})}>{materials.map(m=><option key={m}>{m}</option>)}</select></div></label><NumberInput label="Thickness" value={layer.thickness_nm} unit="nm" onChange={v=>patchLayer(selected,{thickness_nm:v})}/>{/(AlGa|InGa|AlIn|SiGe)/.test(layer.material)&&<NumberInput label="Alloy fraction" value={layer.alloy_fraction??.3} onChange={v=>patchLayer(selected,{alloy_fraction:v})}/>}<NumberInput label="Donors Nᴅ" value={layer.donors_cm3} unit="cm⁻³" onChange={v=>patchLayer(selected,{donors_cm3:v})}/><NumberInput label="Acceptors Nₐ" value={layer.acceptors_cm3} unit="cm⁻³" onChange={v=>patchLayer(selected,{acceptors_cm3:v})}/></div>}<div className="editor compact"><b>Experiment</b><NumberInput label="Temperature" value={project.temperature_k} unit="K" onChange={v=>patch({temperature_k:v})}/><NumberInput label="Mesh" value={project.mesh_spacing_nm} unit="nm" onChange={v=>patch({mesh_spacing_nm:v})}/><NumberInput label="Surface bias" value={project.surface.voltage_v} unit="V" step={.05} onChange={v=>patch({surface:{...project.surface,voltage_v:v}})}/><label className="toggle"><input type="checkbox" checked={project.sweep.enabled} onChange={e=>patch({sweep:{...project.sweep,enabled:e.target.checked}})}/><span>Voltage sweep</span></label>{project.sweep.enabled&&<div className="field-grid"><NumberInput label="Start" value={project.sweep.start_v} unit="V" onChange={v=>patch({sweep:{...project.sweep,start_v:v}})}/><NumberInput label="Stop" value={project.sweep.stop_v} unit="V" onChange={v=>patch({sweep:{...project.sweep,stop_v:v}})}/><NumberInput label="Step" value={project.sweep.step_v} unit="V" onChange={v=>patch({sweep:{...project.sweep,step_v:v}})}/></div>}</div></>}
      {pane==="quantum"&&<div className="pane-content"><div className="info-card accent"><Atom/><div><b>Electron quantum states</b><p>Solves the position-dependent effective-mass Hamiltonian inside the selected window.</p></div></div><label className="toggle prominent"><input type="checkbox" checked={!!project.quantum} onChange={e=>patch({quantum:e.target.checked?{start_nm:0,stop_nm:project.layers.reduce((s,l)=>s+l.thickness_nm,0),states:4}:null})}/><span>Enable Schrödinger solve</span></label>{project.quantum?<><NumberInput label="Window start" value={project.quantum.start_nm} unit="nm" onChange={v=>patch({quantum:{...project.quantum!,start_nm:v}})}/><NumberInput label="Window stop" value={project.quantum.stop_nm} unit="nm" onChange={v=>patch({quantum:{...project.quantum!,stop_nm:v}})}/><NumberInput label="Requested states" value={project.quantum.states} onChange={v=>patch({quantum:{...project.quantum!,states:Math.max(1,Math.round(v))}})}/><div className="state-list"><small>COMPUTED STATES</small>{result?.eigenstates.length?result.eigenstates.map(s=><div key={s.index}><span>ψ{s.index}</span><b>{n(s.energy_ev,4)} eV</b></div>):<p>No states in the current result.</p>}</div></>:<p className="muted-copy">Enable this for quantum wells, heterostructure channels, and HEMT subband analysis. Keep the window around the region of interest for faster solves.</p>}</div>}
      {pane==="settings"&&<div className="pane-content"><div className="settings-group"><small>APPEARANCE</small><label className="field"><span>Color theme</span><div><select value={theme} onChange={e=>setTheme(e.target.value as Theme)}><option value="mocha">Catppuccin Mocha</option><option value="macchiato">Catppuccin Macchiato</option><option value="latte">Catppuccin Latte</option><option value="tokyo">Tokyo Night</option><option value="gruvbox">Gruvbox</option></select></div></label><NumberInput label="Font scale" value={fontScale} unit="%" step={5} onChange={v=>setFontScale(Math.min(125,Math.max(85,v)))}/><div className="segmented"><button className={density==="comfortable"?"active":""} onClick={()=>setDensity("comfortable")}>Comfortable</button><button className={density==="compact"?"active":""} onClick={()=>setDensity("compact")}>Compact</button></div></div><div className="settings-group"><small>NUMERICAL SOLVER</small><NumberInput label="Maximum iterations" value={project.solver.max_iterations} onChange={v=>patch({solver:{...project.solver,max_iterations:Math.round(v)}})}/><NumberInput label="Tolerance" value={project.solver.tolerance} onChange={v=>patch({solver:{...project.solver,tolerance:v}})}/><NumberInput label="Mixing" value={project.solver.mixing} onChange={v=>patch({solver:{...project.solver,mixing:v}})}/><NumberInput label="Preview mesh scale" value={project.solver.preview_scale} unit="×" onChange={v=>patch({solver:{...project.solver,preview_scale:v}})}/></div></div>}
      {pane==="learn"&&<div className="learn-pane"><div className="about-shark"><SharkLogo/><div><h3>Requin</h3><p>1D semiconductor analysis · v0.1.0</p></div></div><h4>Quick start</h4><ol><li>Choose a device template or import a legacy deck.</li><li>Build the layer stack from surface to substrate.</li><li>Set contacts, bias, temperature, and mesh.</li><li>Enable a quantum window when confinement matters.</li><li>Read the convergence status before using a curve.</li></ol><h4>What happens under the hood</h4><div className="learn-equation"><MathText tex="\\nabla\\cdot(\\varepsilon\\nabla\\phi)=-\\rho"/><p>Poisson’s equation converts charge into electrostatic potential and band bending.</p></div><div className="learn-equation"><MathText tex="\\hat H\\psi_i=E_i\\psi_i"/><p>The effective-mass Schrödinger equation finds confined electron energies and wavefunctions.</p></div><h4>Reading the report</h4><p><b>Bands</b> show allowed electron and hole energies. <b>Carriers</b> show mobile charge. <b>Field</b> is the spatial derivative of potential. <b>Wavefunctions</b> show confinement probability. <b>I–V/C–V</b> summarizes voltage sweeps.</p><h4>Model limits</h4><p>Requin is an engineering preview. Current curves are first-order PN diffusion and Schottky thermionic estimates. HEMT analysis is vertical electrostatics and confinement, not drain transport. Unconverged results are diagnostic only.</p></div>}
    </section>
    <section className="workspace">
      <header className="topbar"><div><small>ONE-DIMENSIONAL DEVICE ANALYSIS</small><h1>{project.name}</h1></div><div className="actions export-actions"><button onClick={csv} disabled={!result}><Download/> CSV</button><button onClick={svg} disabled={!result}>SVG</button><button onClick={()=>window.print()} disabled={!result}>PDF</button></div></header>
      <div className="status"><span className={status==="Converged"?"ok":""}/>{status}{result&&<><i/> {result.convergence.iterations} iterations <i/> residual {result.convergence.residual.toExponential(2)}</>}{error&&<strong>{error}</strong>}</div>
      <article className="report">
        <div className="report-title"><div><small>REQUIN COMPUTATIONAL REPORT · {new Date().toLocaleDateString()}</small><h2>Electrostatic and quantum analysis</h2><p>{project.layers.length} layers · {n(project.layers.reduce((s,l)=>s+l.thickness_nm,0),1)} nm · {project.temperature_k} K</p></div><div className="equation"><MathText tex="\\nabla\\cdot(\\varepsilon\\nabla\\phi)=-\\rho"/></div></div>
        <div className="metrics"><div><small>STATUS</small><b>{result?.convergence.converged?"Converged":"Pending"}</b></div><div><small>SURFACE BIAS</small><b>{n(project.surface.voltage_v)} V</b></div><div><small>GRID POINTS</small><b>{result?.position_nm.length??"—"}</b></div><div><small>BOUND STATES</small><b>{result?.eigenstates.length??"—"}</b></div></div>
        <nav className="tabs">{(["bands","carriers","field","wave","sweep"] as ChartKind[]).map(k=><button className={chart===k?"active":""} onClick={()=>setChart(k)} key={k}>{k==="wave"?"Wavefunctions":k==="sweep"?"I–V / C–V":k[0].toUpperCase()+k.slice(1)}</button>)}</nav>
        <section className="figure"><div className="figure-head"><div><small>FIGURE 01</small><h3>{chart==="bands"?"Energy-band diagram":chart==="carriers"?"Mobile carrier concentrations":chart==="field"?"Electric field":chart==="wave"?"Lowest electron wavefunction":"Voltage sweep"}</h3></div></div><div className="series-strip"><span className="blue"/><MathText tex={chart==="bands"?"E_c":chart==="carriers"?"n":chart==="field"?"E":chart==="wave"?"\\psi_1":"J"}/>{(chart==="bands"||chart==="carriers"||chart==="sweep")&&<><span className="mauve"/><MathText tex={chart==="bands"?"E_v":chart==="carriers"?"p":"C"}/></>}</div>{result?<Plot kind={chart} result={result}/>:<div className="empty"><Waves/>Waiting for the numerical core…</div>}<p className="caption">Finite-volume solution on an interface-aligned grid. Preview results are replaced automatically by the full-tolerance solution.</p></section>
        {result?.convergence.warnings.map((w,i)=><div className="warning" key={i}>{w}</div>)}
      </article>
    </section>
  </main>
}
export default App;
